### ISSUE TITLE
 For the image style transfer task

### ISSUE THREAD

**Issue by westream** [poloclub/cnn-explainer#15]

**Comment by westream** [comment]
Hello, your work is very inspiring to me. For the image style transfer task, since the image feature map has been down-sampled, the channel domain information becomes very important. I would like to ask about this method of you, how to use my own trained model to visualize under your framework, or you Have any visualizations done similar tasks? For the convolutional network of this generation task, what knowledge does the convolutional nerve learn. thank you very much

**Comment by xiaohk** [comment]
Thanks for your interests! This issue is related to #2 and #8.

Currently CNN Explainer only supports the Tiny-VGG architecture that we described in our [manuscript](http://arxiv.org/abs/2004.15004). If you want to use a different CNN model, then you would need to modify the code. Here are some functions that you would need to change: https://github.com/poloclub/cnn-explainer/issues/8#issuecomment-624624004.

For GANs model, you can also check out our other work: [GAN Lab](https://github.com/poloclub/ganlab). Both CNN Explainer and GAN Lab aim to help beginners study the mathematical and algorithmic concepts of CNNs and GANs. They are not particularly designed for domain experts to interpret what each neuron has learned. For interpretation tasks, you can check out [Summit](https://github.com/fredhohman/summit/) and some other work.

I will close this issue for now. Feel free to reply or reopen it if you need further help :)
