### ISSUE TITLE
Different settings of the legend ranges after updateCNN

### ISSUE THREAD

**Issue by damien0x0023** [poloclub/cnn-explainer#22]
Hi Wang,
Your work seems fabulous for me to learn from the scratch to deeper understanding of CNN. However, the ranges for the layers doubled after I switch from one image to annther. It makes me confused for a while...

Before Switching:
![image](https://user-images.githubusercontent.com/13963341/91383427-06df8500-e824-11ea-9924-439a97cd86c5.png)

After:
![image](https://user-images.githubusercontent.com/13963341/91383464-18c12800-e824-11ea-9d13-ff127a4a4c09.png)

I thus review your codes and try to find the reason. It is not a piece of cake for me because I am used to work more on the back-end.

![image](https://user-images.githubusercontent.com/13963341/91383645-8e2cf880-e824-11ea-8847-b79f13a23ac3.png)
[-range1/2, range1/2]

During the the code review, I find there are different settings of the ranges btw function drawLegends and updateCNN.
![image](https://user-images.githubusercontent.com/13963341/91383705-b4529880-e824-11ea-9af7-c8590b4ecb1b.png)

[-range1, range1]

It is not a big issue but I still want to confirm that the first one from -range1 /2 to range1 /2 is right, isn't it?

By the way, I wonder if there is a way to present RNN with LSTM like your CNN Explainer.  Could I try it based on your code for a simple RNN in sentiment task? 

Thanks for your job and Hope you good health.

Damein

**Comment by xiaohk** [comment]
Hello Damein, thank you so much for catching this bug and spending so much time to help us debug it!! Your code review skill is very impressive! Yes, both `range1` and `range2` should be halved in `updateCNN()`. It is fixed in 0398f4eebcc7c2e612aec940311718a15a89471a, and the new change is deployed to https://poloclub.github.io/cnn-explainer/ .

Yes, you can apply the same visualization design (e.g., transitions, animations) to present RNNs. Unfortunately, the code base in this repository is very specific to linear CNNs, so I don't think it would be really helpful/easy to clone this repo and make it work for RNNs :(

Thanks again for notifying us about this bug and helping us identify the error! I will close the issue for now, feel free to comment or re-open the issue. Hope you are staying safe too, Damein :)

Jay
