### ISSUE TITLE
Layout messed up

### ISSUE THREAD

**Issue by LqYe** [poloclub/cnn-explainer#25]
Hello,

Kudos to this awesome project!!! I love it.

I just downloaded the repo and I was able to run it locally.  But the layout seems completely messed up. It's not as organized as the live demo. I've tried it on Chrome, Safari and Firefox and they all have the same messed layout. 

I wonder if there is a way to get it fixed. Thanks

See images below:

![image](https://user-images.githubusercontent.com/1787634/101110807-ab453600-358e-11eb-8449-26f5d15a943f.png)
![image](https://user-images.githubusercontent.com/1787634/101110860-d0d23f80-358e-11eb-8d4e-3d629632efdd.png)
![image](https://user-images.githubusercontent.com/1787634/101110883-dcbe0180-358e-11eb-8889-efd1e522084a.png)

**Comment by hamiltondematos** [comment]
Facing the same problem here. Thanks!

**Comment by fredhohman** [comment]
Hi @LqYe and @hamiltondematos. At first glance this looks like a CSS issue, but @xiaohk should be able to help.

Question: are either of you receiving any errors in the console?

**Comment by xiaohk** [comment]
Hey @LqYe and @hamiltondematos, thanks for reaching out to us!

This issue is caused by the newer version of rollup plugin introduced in a0f561787846a4a0afd030032822022d53de1019. It changes the CSS bundle path rule ([rollup-plugin-svelte@6.0.0 release notes](https://github.com/sveltejs/rollup-plugin-svelte/blob/master/CHANGELOG.md#600)). 80ef18b77601b6be145f23f6726837b12d1123ec should fix it. You can try again using the latest clone. Feel free to reopen this issue if the layout still looks weird.
