### ISSUE TITLE
cnn _ explainer in local host

### ISSUE THREAD

**Issue by swetha311295** [poloclub/cnn-explainer#28]
hi ... i tried to rub the package.jason in eclipse . the message console shows  the local host port . but when i open the local host in chrome the CNN explainer remains blank.

**Comment by xiaohk** [comment]
Hello, did you run the following two commands in your terminal (I guess you use terminal inside Eclipse)?

```bash
npm install
npm run dev
```

**Comment by swetha311295** [comment]
hello ... i did run the two commands.in the cnn explainer   it shows an option to add only one input image. i am unable to add  the rest of the images .

**Comment by xiaohk** [comment]
Nice, it seems you can run CNN Explainer locally now :)

Do you mean passing your own input image to the pre-trained model? What do you mean by the "rest of the images"? CNN Explainer right now only supports visualizing the model with one input image. You can add new input image as shown below:

![d1](https://user-images.githubusercontent.com/15007159/113521114-6db8df80-9565-11eb-90af-724b8d2b3391.png)
![demo2](https://user-images.githubusercontent.com/15007159/113521116-6f82a300-9565-11eb-8b82-8652b87e3e82.png)

**Comment by swetha311295** [comment]
hello again ..  my issue is that when i open the server it dosent load properly. i have the java script enabled for the chrome . i tried to open it in a different web browser like Edge . but i still face the issue
![1](https://user-images.githubusercontent.com/76578078/113523020-83e69000-95a5-11eb-9c44-ce43194b7176.png)

**Comment by xiaohk** [comment]
I see. The images do not show up because the web browser is preventing you from accessing local file for security concerns. Usually using a localhost web server should fix it, which should have set up by running `npm run dev`.

Some steps to try next:

1. Did you modify the CNN Explainer source code? If so, you can try to clone this repo again and run it directly from there.
2. Can I see your terminal where you ran `npm install` and `npm run dev`? Make sure your current working directory is under `cnn-explainer-master`.

**Comment by swetha311295** [comment]
thank you so much... I tried with a new copy of the repo... It worked fine!!
