### ISSUE TITLE
about retraining cnn explainer

### ISSUE THREAD

**Issue by BobBogart** [poloclub/cnn-explainer#31]
Hello,it's really happy using cnn explainer.Yet I have a question,how could we use it to train a cnn for things like sword with around 200 kinds?

**Comment by xiaohk** [comment]
Hello @BobBogart,

I am happy to hear that you like CNN Explainer! 

To use CNN Explainer with your own model and dataset, you can check out these related issues: #2, #8, #15. Some functions you want to look into are listed [in this comment](https://github.com/poloclub/cnn-explainer/issues/8#issuecomment-624624004).

If you want to train Tiny-VGG on the sword dataset, you can check out issue #14. They have [successfully trained]((https://github.com/NikaMasa51/Study_CNN_Explainer)) Tiny-VGG on their plant dataset and visualize the CNN with CNN Explainer. Since 200 classes are a lot, perhaps you can try to choose 10 most distinct classes as a first step. Later you can modify the CNN Explainer UI code to have more output neurons (you can keep the number of neurons in hidden layers as 10).

I will close the issues for now. Feel free to reach out if you need further help :)

**Comment by BobBogart** [comment]
Thank you very much!



---Original---
From: "Jay ***@***.***&gt;
Date: Sun, Jun 13, 2021 18:59 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [poloclub/cnn-explainer] about retraining cnn explainer (#31)




 
Hello @BobBogart,
 
I am happy to hear that you like CNN Explainer!
 
To use CNN Explainer with your own model and dataset, you can check out these related issues: #2, #8, #15. Some functions you want to look into are listed in this comment.
 
If you want to train Tiny-VGG on the sword dataset, you can check out issue #14. They have successfully trained Tiny-VGG on their plant dataset and visualize the CNN with CNN Explainer. Since 200 classes are a lot, perhaps you can try to choose 10 most distinct classes as a first step. Later you can modify the CNN Explainer UI code to have more output neurons (you can keep the number of neurons in hidden layers as 10).
 
I will close the issues for now. Feel free to reach out if you need further help :)
