### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by freedom521jin** [poloclub/cnn-explainer#32]
I fellow your steps,and got the error:
![image](https://user-images.githubusercontent.com/23634449/124215601-f45e6800-db26-11eb-89bf-980d896cda9f.png)
---------------------------------------------------
So,please help me to fix it,thx

**Comment by xiaohk** [comment]
Good catch @freedom521jin, thank you for letting us know!

It is due to a breaking change of `svelte` 10 days ago (https://github.com/sveltejs/svelte/issues/5907)

https://github.com/poloclub/cnn-explainer/commit/2b75d287704c8a7134a99798cd3b771e896337fc should have fixed it. Please clone the latest version and try again. Let us know if you encounter any issues :)

**Comment by freedom521jin** [comment]
> Good catch @freedom521jin, thank you for letting us know!
> 
> It is due to a breaking change of `svelte` 10 days ago ([sveltejs/svelte#5907](https://github.com/sveltejs/svelte/issues/5907))
> 
> [2b75d28](https://github.com/poloclub/cnn-explainer/commit/2b75d287704c8a7134a99798cd3b771e896337fc) should have fixed it. Please clone the latest version and try again. Let us know if you encounter any issues :)

It's worked ,thx!
