### ISSUE TITLE
How can i change the input_image_size ?

### ISSUE THREAD

**Issue by miiiingi** [poloclub/cnn-explainer#46]
I am trying to change input_image_size(the default value is 64). but I am not familiar with front-end module.
Is there anyone who can help me?

**Comment by baobobby** [comment]
you will have to change the inputsize in the first line of cnn-tf.js. And then you have to make sure the image size in folder *\cnn-explainer-master\public\assets\img is the same as the value you type in cnn-tf.js. If the size of these images is different, you must transfer them to the size you want. After that you may run the programm as expected. 

In cnn-tf.js the developer was going to give a way that can automatically adapt the input image size to the value which is customized by users, but the code is not yet completed, so we have to change the size of the images to the value we customize in cnn-tf.js manually.

**Comment by miiiingi** [comment]
When I edit the first line of cnn-tf.js, the web browser only show me the  blank page.. 
I am not familiar with node js, so I do not know what can i do for correct view of the web browser.. 
plz tell me What can i do this error?? 

![image](https://user-images.githubusercontent.com/71509516/188070885-f11bf42e-2cea-4d65-b60f-e33f2f140af4.png)

Best regards.

**Comment by baobobby** [comment]
I guess you want to change the input size to a larger one, right? Well as I wrote above, except the code modification of the first line in cnn-tf.js, you will also have to resize the images in folder *\cnn-explainer-master\public\assets\img to the same value in the first line of cnn-tf.js. 

The reason why only blank page displayed may be that you didnt transfer the images' size in the folder I mentioned and the program found that the input image size is not conformed with the value you set in cnn-tf.js, so it rejected the next move but gave a blank page.

Pls remember that the Programm is only to show your CNN but with the images in the folder I mentioned as its input. Which means, **that you must keep the sizes of those images, the input size you set in cnn-tf.js and of course the input size you set in your CNN exactly the SAME.**

A way to change the size of image is using **_PowerToys_**. It is a powerful image editor that is developed by Microsoft, you can easily resize the images you selected with this tool.

CNN-Explainer have the ablity to crop a bigger image to a smaller input size (the size that be set in the first line of cnn-tf.js). But when the size of input image is smaller than the input size in cnn-tf.js, the program will reject the next move. Because there are no codes for resizing the input image. So in this situation we must resize the images manually.

**Comment by miiiingi** [comment]
Okay. I will try to resize those images. Thank you!!

**Comment by baobobby** [comment]
You are welcom. Have fun with modifying CNN Explainer.
