### ISSUE TITLE
fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by alizezhu** [poloclub/cnn-explainer#7]
Dear poloclub,
I run into this error msg. Could you let me know how to solve it? thanks a lot

G:\PY\cnnexplainer>git clone git@github.com:poloclub/cnn-explainer.git
Cloning into 'cnn-explainer'...
The authenticity of host 'github.com (140.82.118.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.118.3' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by xiaohk** [comment]
Hello, `git@github.com:poloclub/cnn-explainer.git` works fine for me.

GitHub had some [system issue](https://www.githubstatus.com) from 5/5 0:45-2:51 UTC, maybe that's why you couldn't access the server. GitHub also has a [troubleshooting page](https://help.github.com/en/github/authenticating-to-github/error-permission-denied-publickey) for the error `Permission denied (publickey)`. You might find it useful.

Let us know if you still cannot connect to this repo. I will close this issue for now.
